### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zly987** [siemens/powergym#1]
An error occurred while running random_agent.py ,as

### 
Traceback (most recent call last):
  File "E:/powergym-master/random_agent.py", line 225, in <module>
    run_random_agent(args, worker_idx=None, use_plot=args.use_plot, print_step=False)
  File "E:/powergym-master/random_agent.py", line 53, in run_random_agent
    env = make_env(args.env_name, worker_idx=worker_idx)
  File "E:\powergym-master\powergym\env_register.py", line 287, in make_env
    return Env(folder_path, base_info, dss_act)
  File "E:\powergym-master\powergym\env.py", line 240, in __init__
    self.load_profile = LoadProfile(\
  File "E:\powergym-master\powergym\loadprofile.py", line 24, in __init__
    for f in os.listdir(self.loadshape_path):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'E:\\powergym-master\\systems\\13Bus\\loadshape'

How to solve this problem?

**Comment by nejch** [comment]
@bruinWang it'd be good to add some basic tests here so that these reports can be reproduced.

**Comment by bruinWang** [comment]
@zly987 @nejch  bug fixed and tested! 
@zly987  please let me know if it still creates problem for you. Otherwise, I will close the issue

**Comment by zly987** [comment]
new bug


Traceback (most recent call last):
  File "E:/powergym-master/random_agent.py", line 228, in <module>
    run_random_agent(args, worker_idx=None, use_plot=args.use_plot, print_step=False)
  File "E:/powergym-master/random_agent.py", line 55, in run_random_agent
    env = make_env(args.env_name, worker_idx=worker_idx)
  File "E:\powergym-master\powergym\env_register.py", line 287, in make_env
    return Env(folder_path, base_info, dss_act)
  File "E:\powergym-master\powergym\env.py", line 257, in __init__
    self.circuit = Circuits(os.path.join(self.dss_folder_path, self.dss_file),
  File "E:\powergym-master\powergym\circuit.py", line 43, in __init__
    self.initialize()
  File "E:\powergym-master\powergym\circuit.py", line 128, in initialize
    self.compile(disable = False)
  File "E:\powergym-master\powergym\circuit.py", line 88, in compile
    self.dss.Text.Command = "compile " + self.dss_file
  File "E:\Anaconda\envs\powergym\lib\site-packages\dss\dss_capi_gr\IText.py", line 20, in Command
    Value = Value.encode(self._api_util.codec)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 26-28: ordinal not in range(128)


This problem was encountered in other projects before. It was solved by deleting the parameters of a function. I don't know whether this problem is the problem of my computer itself or the need to modify the code.

**Comment by bruinWang** [comment]
@zly987 I have tested both on ubuntu and windows 10, starting a new directory, cloning the repo, install requirements, and run python random_agent.py. However, I cannot recreate your error message. Could you let us know how to recreate this bug?

**Comment by zly987** [comment]
Sorry, the problem is on my computer,I'm very confused about it. But I replaced another computer and it can run successfully.

**Comment by bruinWang** [comment]
No worries. @zly987 thanks for using the env, please let us know if you have further feedback. 
I will close this issue.
